import{a as v,S as _,i as n}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&a(f)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const S="53445349-55a99b0310e27289c38888bf9",A="https://pixabay.com/api/",P=15;async function h(r,o=1){const e={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:o};return(await v.get(A,{params:e})).data}const y=document.getElementById("gallery"),l=document.querySelector(".js-load-more"),u=document.querySelector(".loader"),$=new _(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const o=r.map(e=>`
      <li class="gallery__item">
        <a class="gallery__link" href="${e.largeImageURL}">
          <img class="gallery__image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${e.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${e.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${e.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${e.downloads}</span></p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",o),$.refresh()}function q(){y.innerHTML=""}function p(){u&&u.classList.remove("is-hidden")}function L(){u&&u.classList.add("is-hidden")}function b(){l&&l.classList.remove("is-hidden")}function c(){l&&l.classList.add("is-hidden")}const w=document.getElementById("search-form"),B=w.elements["search-text"],m=document.querySelector(".js-load-more");let d="",i=1;const E=15;w.addEventListener("submit",I);m==null||m.addEventListener("click",H);async function I(r){r.preventDefault();const o=B.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search query",timeout:3e3});return}d=o,i=1,q(),c(),p();try{const e=await h(d,i);if(!e||!Array.isArray(e.hits)||e.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",timeout:4e3});return}g(e.hits);const a=e.totalHits||0;a>i*E?b():(c(),n.info({message:"We're sorry, but you've reached the end of search results.",timeout:4e3})),n.success({title:"Success",message:`Found ${a} images`,timeout:2e3})}catch(e){console.error("Error fetching images:",e),n.error({title:"Error",message:"Something went wrong while fetching images.",timeout:3e3})}finally{L()}}async function H(){if(d){i+=1,p(),c();try{const r=await h(d,i);if(!r||!Array.isArray(r.hits)||r.hits.length===0){n.info({message:"We're sorry, but you've reached the end of search results.",timeout:4e3}),c();return}g(r.hits);const o=document.querySelector(".gallery__item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const e=r.totalHits||0;i*E>=e?(c(),n.info({message:"We're sorry, but you've reached the end of search results.",timeout:4e3})):b()}catch(r){console.error("Error fetching more images:",r),n.error({title:"Error",message:"Something went wrong while fetching more images.",timeout:3e3})}finally{L()}}}
//# sourceMappingURL=index.js.map
