import{a as E,S as _,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&n(f)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const v="53445349-55a99b0310e27289c38888bf9",S="https://pixabay.com/api/",A=15;async function m(r,o=1){const e={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:A,page:o};return(await E.get(S,{params:e})).data}const y=document.getElementById("gallery"),i=document.querySelector(".js-load-more"),u=document.querySelector(".loader"),P=new _(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const o=r.map(e=>`
      <li class="gallery__item">
        <a class="gallery__link" href="${e.largeImageURL}">
          <img class="gallery__image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${e.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${e.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${e.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${e.downloads}</span></p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",o),P.refresh()}function B(){y.innerHTML=""}function g(){u&&u.classList.remove("is-hidden")}function p(){u&&u.classList.add("is-hidden")}function b(){i&&(i.style.display="block",i.disabled=!1)}function l(){i&&(i.style.display="none",i.disabled=!0)}const L=document.getElementById("search-form"),$=L.elements["search-text"],q=document.querySelector(".js-load-more");let d="",c=1;const w=15;l();L.addEventListener("submit",M);q.addEventListener("click",I);async function M(r){r.preventDefault();const o=$.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search query",timeout:3e3});return}d=o,c=1,B(),l(),g();try{const e=await m(d,c);if(!e||!Array.isArray(e.hits)||e.hits.length===0){a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",timeout:4e3});return}h(e.hits);const n=e.totalHits||0;n>w?b():l(),a.success({title:"Success",message:`Found ${n} images`,timeout:2e3})}catch(e){console.error("Error fetching images:",e),a.error({title:"Error",message:"Something went wrong while fetching images.",timeout:3e3})}finally{p()}}async function I(){if(d){c+=1,g(),l();try{const r=await m(d,c);if(!r||!Array.isArray(r.hits)||r.hits.length===0){l(),a.info({message:"We're sorry, but you've reached the end of search results.",timeout:4e3});return}h(r.hits);const o=document.querySelector(".gallery__item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const e=r.totalHits||0;c*w>=e?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",timeout:4e3})):b()}catch(r){console.error("Error fetching more images:",r),a.error({title:"Error",message:"Something went wrong while fetching more images.",timeout:3e3})}finally{p()}}}
//# sourceMappingURL=index.js.map
